"""Hwll

Revision ID: 0131719c6439
Revises: a5ad76290d43
Create Date: 2025-09-04 10:17:04.243850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0131719c6439"
down_revision: Union[str, Sequence[str], None] = "a5ad76290d43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["shopify_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ab_tests_id"), "ab_tests", ["id"], unique=False)
    op.create_table(
        "variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ab_test_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("conversions", sa.Integer(), nullable=True),
        sa.Column("conversion_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ab_test_id"],
            ["ab_tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_variants_id"), "variants", ["id"], unique=False)
    op.add_column("brand_voice", sa.Column("example", sa.Text(), nullable=True))
    op.add_column("brand_voice", sa.Column("guidelines", sa.Text(), nullable=True))
    op.drop_column("brand_voice", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "brand_voice",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("brand_voice", "guidelines")
    op.drop_column("brand_voice", "example")
    op.drop_index(op.f("ix_variants_id"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_ab_tests_id"), table_name="ab_tests")
    op.drop_table("ab_tests")
    # ### end Alembic commands ###
