"""Add ScheduledABTestRotation model

Revision ID: 23abce99558c
Revises: bf0d804a1d47
Create Date: 2025-09-04 10:26:47.661118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23abce99558c"
down_revision: Union[str, Sequence[str], None] = "bf0d804a1d47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_ab_test_rotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ab_test_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("next_rotation_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=True),
        sa.Column("last_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ab_test_id"],
            ["ab_tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["shopify_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_ab_test_rotations_id"),
        "scheduled_ab_test_rotations",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_ab_test_rotations_id"),
        table_name="scheduled_ab_test_rotations",
    )
    op.drop_table("scheduled_ab_test_rotations")
    # ### end Alembic commands ###
