"""Add brand voice table and keyword support

Revision ID: a5ad76290d43
Revises: 87cc755db627
Create Date: 2025-09-03 21:58:37.703519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5ad76290d43"
down_revision: Union[str, Sequence[str], None] = "87cc755db627"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_voice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["shopify_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brand_voice_id"), "brand_voice", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brand_voice_id"), table_name="brand_voice")
    op.drop_table("brand_voice")
    # ### end Alembic commands ###
