"""add usage table

Revision ID: b32c6c978243
Revises: f57475222542
Create Date: 2025-09-15 16:00:17.543042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b32c6c978243"
down_revision: Union[str, Sequence[str], None] = "f57475222542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("feature", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_feature"), "usage", ["feature"], unique=False)
    op.create_index(op.f("ix_usage_id"), "usage", ["id"], unique=False)
    op.create_index(
        op.f("ix_permissions_action"), "permissions", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_permissions_resource"), "permissions", ["resource"], unique=False
    )
    op.drop_column("permissions", "updated_at")
    op.drop_column("permissions", "created_at")
    op.drop_column("permissions", "group")
    op.drop_column("permissions", "description")
    op.add_column(
        "shopify_users",
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shopify_users", "trial_ends_at")
    op.add_column(
        "permissions",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "permissions",
        sa.Column("group", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "permissions",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "permissions",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_permissions_resource"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_action"), table_name="permissions")
    op.drop_index(op.f("ix_usage_id"), table_name="usage")
    op.drop_index(op.f("ix_usage_feature"), table_name="usage")
    op.drop_table("usage")
    # ### end Alembic commands ###
