"""Add active_variant_id to ABTest

Revision ID: bf0d804a1d47
Revises: 0131719c6439
Create Date: 2025-09-04 10:21:18.631493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf0d804a1d47"
down_revision: Union[str, Sequence[str], None] = "0131719c6439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ab_tests", sa.Column("active_variant_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "ab_tests", "variants", ["active_variant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ab_tests", type_="foreignkey")
    op.drop_column("ab_tests", "active_variant_id")
    # ### end Alembic commands ###
